# Generated by Django 4.2.5 on 2024-01-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentTrove', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Invitation',
        ),
        migrations.RenameModel(
            old_name='programming_languages',
            new_name='ProgrammingLanguages',
        ),
        migrations.RenameModel(
            old_name='Worker_programming_languages',
            new_name='WorkerProgrammingLanguages',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='talentTrove.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='talentTrove.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='talentTrove.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='account_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='field_visibility',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='worker',
            name='prefered_style_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='talentTrove.city'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='prefered_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='talentTrove.specialization'),
        ),
    ]
