# Generated by Django 4.2.5 on 2024-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentTrove', '0002_rename_invite_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
