# Generated by Django 4.2.5 on 2024-01-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentTrove', '0003_invitation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
