# Generated by Django 4.2.5 on 2024-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentTrove', '0004_alter_city_name_alter_programminglanguages_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
